project_structure:
    build: build
    contracts: contracts
    interface: contracts/interface
    scripts: scripts
    tests: test

networks:
  default: development

  development:
    cmd_settings:
      gas_limit: 40000000
      accounts: 100
      default_balance: 100000000
      mnemonic: clock radar mass judge dismiss just intact mind resemble fringe diary casino
      evm_version: berlin
      port: 8546

compiler:
  solc:
    version: 0.8.4
    remappings:
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.9.3/contracts"
      - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.3/contracts"

hypothesis:
  max_examples: 10
dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.3
  - OpenZeppelin/openzeppelin-contracts@4.9.3